revision:    2021-05-19 (Wed) 06:36:21
name:        my-app
description: ISLEcode Svelte template
version:     1.0.0
private:     true
keywords:    [ svelte ]

# ~version    Approximately equivalent to version (Cf. https://bit.ly/3eoeOGe)
# ^version    Compatible with version (Cf. https://bit.ly/3epwBww)
# version     Must match version exactly
# >version    Must be greater than version (also >=, <, <=)
# 1.2.x       1.2.0, 1.2.1, etc., but not 1.3.0
# *           Matches any version
# latest      Obtains latest release

dependencies:
#   '@sendgrid/mail':                            ^7.4.2     # SendGrid v3 API (https://sendgrid.com/docs/api-reference)

devDependencies:
#   '@babel/core':                               ^7.0.0     # Javascript compiler (https://babeljs.io/docs)
#   '@babel/plugin-syntax-dynamic-import':       ^7.0.0     # - https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import
#   '@babel/plugin-transform-object-assign':     ^7.12.13   # - https://babeljs.io/docs/en/babel-plugin-transform-object-assign
#   '@babel/plugin-transform-runtime':           ^7.0.0     # - https://babeljs.io/docs/en/babel-plugin-transform-runtime
#   '@babel/preset-env':                         ^7.13.12   # - https://babeljs.io/docs/en/babel-preset-env
#   '@babel/preset-typescript':                  ^7.13.0    # - https://babeljs.io/docs/en/babel-preset-typescript
#   '@babel/runtime':                            ^7.0.0     # - https://babeljs.io/docs/en/babel-runtime
#   'bootstrap':                                 latest     # Bootstrap UI framework
#   cssnano:                                     ^4.1.10    # CSS minifier for PostCSS (http://cssnano.co)
#   github-buttons:                              ^2.15.0    # Ready made GitHub buttons (https://buttons.github.io)
#   husky:                                       ^4.3.8     # Improve your commits (https://typicode.github.io/husky)
#   lint-staged:                                 ^10.5.4    # Linter for Git staged files (https://github.com/okonet/lint-staged)
#   mdsvex:                                      ^0.8.9     # Markdown Svelte preprocessor (https://github.com/pngwn/MDsveX)
#   netlify-lambda:                              ^2.0.3
#   npm-run-all:                                 ^4.1.5
#   postcss:                                     ^8.2.8     # Transform CSS with Javascript (https://postcss.org)
#   postcss-cli:                                 ^8.3.1     # - https://github.com/postcss/postcss-cli
#   postcss-import:                              ^14.0.0    # - https://github.com/postcss/postcss-import
#   postcss-load-config:                         ^3.0.1     # - https://github.com/postcss/postcss-load-config
#   postcss-preset-env:                          ^6.7.0     # - https://github.com/csstools/postcss-preset-env
#   prettier:                                    ^2.2.1     # Opiniated code formatter (https://prettier.io)
#   prettier-plugin-svelte:                      ^2.2.0     # - https://github.com/sveltejs/prettier-plugin-svelte
#   remark:                                      latest     # Unified processor to parse and serialize Markdown
#   remark-autolink-headings:                    ^6.0.1     # - https://github.com/remarkjs/remark-autolink-headings
#   remark-slug:                                 ^6.0.0     # - https://github.com/remarkjs/remark-slug
    rollup:                                      ^2.3.4     # EcmaScript bundler (https://rollupjs.org)
#   '@rollup/plugin-babel':                      ^5.0.0     # - https://github.com/rollup/plugins
    '@rollup/plugin-commonjs':                   ^17.0.0    # - (idem)
    '@rollup/plugin-node-resolve':               ^11.0.0    # - (idem)
#   '@rollup/plugin-replace':                    ^2.4.0     # - (idem)
    'rollup-plugin-css-only':                    ^3.1.0
    'rollup-plugin-livereload':                  ^2.0.0
    rollup-plugin-svelte:                        ^7.0.0     # - https://github.com/sveltejs/rollup-plugin-svelte
    rollup-plugin-terser:                        ^7.0.0     # - https://github.com/TrySound/rollup-plugin-terser
    '@rollup/plugin-typescript':                 ^8.0.0     # - https://github.com/rollup/plugins
#   '@rollup/plugin-url':                        ^5.0.0     # - (idem)
#   sass:                                        ^1.32.8    # SASS compiler (https://github.com/sass/dart-sass)
    svelte:                                      ^3.37.0    # Cybernetically enhanced apps (https://github.com/sveltejs/svelte)
    svelte-check:                                ^1.0.46    # - Svelte linter (https://github.com/sveltejs/language-tools)
#   '@sveltejs/adapter-static':                  ^1.0.0-next.8
#   '@sveltejs/adapter-netlify':                 ^1.0.0-next.4
#   '@sveltejs/kit':                             ^1.0.0-next.76
    svelte-preprocess:                           ^4.6.9     # - Preprocessor (https://github.com/sveltejs/svelte-preprocess)
#   tailwindcss:                                 ^2.0.4
    '@tsconfig/svelte':                          ^1.0.10    # Base Svelte Typescript config (https://github.com/tsconfig/bases)
    typescript:                                  ^4.0.3     # Typescript compiler (https://github.com/Microsoft/TypeScript)
    tslib:                                       ^2.0.1     # - Typescript runtime library (https://github.com/Microsoft/tslib)
#   '@types/aws-lambda':                         ^8.10.73   # - AWS Lambda (https://github.com/DefinitelyTyped/DefinitelyTyped)
#   '@types/compression':                        ^1.7.0     # - Compression (https://github.com/DefinitelyTyped/DefinitelyTyped)
#   '@types/node':                               ^14.11.1   # - NodeJS (https://github.com/DefinitelyTyped/DefinitelyTyped)
#   '@types/polka':                              ^0.5.1     # - Micro web server (https://github.com/lukeed/polka)
#   unist-util-visit:                            ^2.0.3     # Visit nodes (https://github.com/syntax-tree/unist-util-visit)
#   vite:                                        ^2.1.5     # Web dev build tool (https://github.com/vitejs/vite)
    sirv-cli:                                    ^1.0.0     # Serving static files (https://github.com/lukeed/sirv)

