# Cf. https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
revision                              : 2021-06-13 (Sun) 12:34:50
extends                               : '@tsconfig/svelte/tsconfig.json' # Cf. https://www.npmjs.com/package/@tsconfig/svelte
compilerOptions                       :
#   moduleResolution                  : node
#   module                            : es2020
    lib                               : [ dom, dom.iterable, es2018, es2019, es2020, esnext ]
    target                            : es2017
#   importsNotUsedAsValues            : error   # svelte-preprocess cannot figure out whether you have a value or a type, so
#                                               # tell TypeScript to enforce using `import type` instead of `import` for Types.
#   isolatedModules                   : true
    removeComments                    : true
    resolveJsonModule                 : true
    types                             : [ 'node', 'jest' ]
#   sourceMap                         : true    # To have warnings/errors of the Svelte compiler at the correct position
#                                               # enable source maps by default.
#   esModuleInterop                   : true
#   skipLibCheck                      : true
#   forceConsistentCasingInFileNames  : true    # Why make short names while you make them terribly long!
#   baseUrl                           : .
#   allowJs                           : true
#   checkJs                           : true
#   paths                             :
#       '$app/*'                      : [ .svelte/dev/runtime/app/*, .svelte/build/runtime/app/* ]
#       '$service-worker'             : [ .svelte/build/runtime/service-worker ]
#       '$lib/*'                      : [ src/lib/* ]
include                               : [ src/**/*.d.ts, src/**/*.js, src/**/*.ts, src/**/*.svelte ]
exclude                               : [ _in/*, src/**/*.test.ts, node_modules/*, __sapper__/*, docs/* ]

# __END__
