<div id="utilsModal___BV_modal_outer_"><div id="utilsModal" role="dialog" class="modal fade show d-block" style="padding-right: 15px;"><div class="modal-dialog modal-lg"><div tabindex="-1" role="document" aria-labelledby="utilsModal___BV_modal_header_" aria-describedby="utilsModal___BV_modal_body_" class="modal-content"><header id="utilsModal___BV_modal_header_" class="modal-header"><h5 class="modal-title"><div><svg role="presentation" width="16" height="16" viewBox="0 0 512 512" class="fa-icon"><path d="M173.9 439.4L7.5 273C-2.5 263-2.5 246.8 7.5 236.8L43.7 200.6C53.7 190.6 69.9 190.6 79.9 200.6L192 312.7 432.1 72.6C442.1 62.6 458.3 62.6 468.3 72.6L504.5 108.8C514.5 118.8 514.5 135 504.5 145L210.1 439.4C200.1 449.4 183.9 449.4 173.9 439.4z"></path></svg>
                    Invoice utilities
                </div></h5><button type="button" aria-label="Close" class="close">×</button></header><div id="utilsModal___BV_modal_body_" class="modal-body"> <form class="form-horizontal"><fieldset id="__BVID__158" role="group" class="b-form-group form-group"><!----><div role="group" class=""><div label-size="sm" role="group" class="input-group input-group-sm"><div class="input-group-prepend"><div class="input-group-text">QR reference number</div></div><input id="__BVID__159" type="text" placeholder="QR reference number" value="" class="input-utilsField form-control"> <div class="input-group-append"><!----></div> <button type="submit" class="btn btn-primary btn-sm">
                                Validate
                            </button></div><!----><!----><!----></div></fieldset></form> <hr> <form class="form-horizontal"><fieldset id="__BVID__160" role="group" class="b-form-group form-group"><!----><div role="group" class=""><div role="group" class="input-group input-group-sm"><div class="input-group-prepend"><div class="input-group-text">Account</div></div><input id="__BVID__161" type="text" placeholder="IBAN" value="" class="input-utilsField form-control"> <div class="input-group-append"><!----></div> <button type="submit" class="btn btn-primary btn-sm">
                                Validate
                            </button></div><!----><!----><!----></div></fieldset></form> <hr> <form class="form-horizontal"><fieldset id="__BVID__162" role="group" class="b-form-group form-group"><!----><div role="group" class=""><div role="group" class="input-group input-group-sm"><div class="input-group-prepend"><div class="input-group-text">QR IBAN</div></div><input id="__BVID__163" type="text" placeholder="QR IBAN" value="" class="input-utilsField form-control"> <div class="input-group-append"><!----></div> <button type="submit" class="btn btn-primary btn-sm">
                                Validate
                            </button></div><!----><!----><!----></div></fieldset></form> <hr> <form class="form-horizontal"><fieldset id="__BVID__164" role="group" class="b-form-group form-group"><!----><div role="group" class=""><div role="group" class="input-group input-group-sm"><div class="input-group-prepend"><div class="input-group-text">Creditor reference</div></div><input id="__BVID__165" type="text" placeholder="Creditor Reference" value="" class="input-utilsField form-control"> <div class="input-group-append"><!----></div> <button type="submit" class="btn btn-primary btn-sm">
                                Validate
                            </button></div><!----><!----><!----></div></fieldset></form> </div><footer id="utilsModal___BV_modal_footer_" class="modal-footer"><div class="w-100"><button type="button" class="btn float-right btn-primary btn-sm">
                        Close
                    </button></div></footer></div></div></div><div id="utilsModal___BV_modal_backdrop_" class="modal-backdrop fade
show"></div></div>
